name: Build PyAudio Wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout PyAudio
        uses: actions/checkout@v4
        with:
          repository: CristiFati/pyaudio
      
      - name: Generate pixi.toml
        run: |
          cat > pixi.toml <<EOF
          [workspace]
          authors = ["BakaDream <2507457629@qq.com>"]
          channels = ["conda-forge"]
          name = "audio-build"
          platforms = ["osx-arm64"]
          version = "0.1.0"

          [tasks]

          [environments.audio-build.dependencies]
          python = "${{ matrix.python-version }}"
          portaudio = ">=19.7.0,<20"
          delocate = ">=0.13.0,<0.14"
          pip = "*"
          EOF

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: false
          run-install: true  # 先不运行安装，我们将手动配置
          environments: audio-build
          activate-environment: audio-build


      - name: Build wheel
        run: |
          # 明确使用指定环境运行pip
          pixi run --env audio-build pip wheel $GITHUB_WORKSPACE -w dist
          
          # 检查生成的wheel文件
          ls -la dist/

      - name: Delocate wheel
        run: |
          mkdir -p wheelhouse
          pixi run --env audio-build delocate-wheel -w wheelhouse dist/*.whl
          
          # 检查处理后的wheel文件
          ls -la wheelhouse/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyaudio-wheels-py${{ matrix.python-version }}
          path: wheelhouse/*.whl
          if-no-files-found: error
