name: Build PyAudio Wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout PyAudio
        uses: actions/checkout@v4
        with:
          repository: CristiFati/pyaudio

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: false
          run-install: false  # 先不运行安装，我们将手动配置
          # environments: audio-build
          # activate-environment: audio-build

      - name: Create and configure pixi environment
        run: |
          # 初始化pixi项目
          pixi init
          
          # 创建并配置环境
          pixi env create audio-build
          pixi add --env audio-build python=${{ matrix.python-version }}
          pixi add --env audio-build portaudio
          pixi add --env audio-build delocate
          pixi add --env audio-build pip
          
          # 验证环境
          pixi list --env audio-build
          
          # 确保环境被激活
          echo "Activating environment"
          source <(pixi env activate audio-build)

      - name: Build wheel
        run: |
          # 明确使用指定环境运行pip
          pixi run --env audio-build pip wheel $GITHUB_WORKSPACE -w dist
          
          # 检查生成的wheel文件
          ls -la dist/

      - name: Delocate wheel
        run: |
          mkdir -p wheelhouse
          pixi run --env audio-build delocate-wheel -w wheelhouse dist/*.whl
          
          # 检查处理后的wheel文件
          ls -la wheelhouse/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyaudio-wheels-py${{ matrix.python-version }}
          path: wheelhouse/*.whl
          if-no-files-found: error
